name: spry_benchmark
description: Spry benchmark tests
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.5
  path: ^1.8.0
  shelf: ^1.4.0
  spry: ^0.4.0

dev_dependencies:
  lints: ^2.0.0
