version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
  - package-ecosystem: pub
    directory: /packages/spry_fsrouter
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
  - package-ecosystem: pub
    directory: /packages/spry_router
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
  - package-ecosystem: pub
    directory: /packages/spry_static
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
