version: 2
updates:
  # Documentation
  - package-ecosystem: npm
    directory: docs
    schedule:
      interval: daily

  # benchmark
  - package-ecosystem: pub
    directory: benchmark
    schedule:
      interval: daily

  # Spry
  - package-ecosystem: pub
    directory: packages/spry
    schedule:
      interval: daily

  # Spry Interceptors
  - package-ecosystem: pub
    directory: packages/spry_interceptor
    schedule:
      interval: daily

  # Spry JSON
  - package-ecosystem: pub
    directory: packages/spry_json
    schedule:
      interval: daily

  # Spry Router
  - package-ecosystem: pub
    directory: packages/spry_router
    schedule:
      interval: daily

  # Spry Session
  - package-ecosystem: pub
    directory: packages/spry_session
    schedule:
      interval: daily

  # Spry Filesystem Router
  - package-ecosystem: pub
    directory: packages/spry_fsrouter
    schedule:
      interval: daily