version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily

  # Docs
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_static
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_interceptor
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_router
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_fsrouter
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_session
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_json
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_urlencoded
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /packages/spry_multer
    schedule:
      interval: daily
