name: workspace
description: The Spry framework workspace.
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

spry:
  packages:
    - packages/**
  dependabot_version: 2

dependencies:
  glob: ^2.1.1
  path: ^1.8.3
  yaml: ^3.1.1
  yaml_edit: ^2.1.0
