name: spry
description: Spry is an HTTP middleware framework for Dart to make web applications and APIs server more enjoyable to write.
version: 3.0.0-dev.1
homepage: https://spry.fun
repository: https://github.com/odroe/spry

environment:
  sdk: ^3.1.2

dependencies:
  consolekit: ^0.0.3
  crypto: ^3.0.3
  dotenv: ^4.2.0
  logging: ^1.2.0
  meta: ^1.11.0
  path: ^1.9.0
  routingkit: ^0.1.2
  webfetch: ^0.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.23.1
