name: spry
description: Spry is an HTTP middleware framework for Dart to make web applications and APIs server more enjoyable to write.
version: 3.0.0-dev.1
homepage: https://spry.fun
repository: https://github.com/odroe/spry

environment:
  sdk: ^3.1.2

dependencies:
  stdweb: ^0.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.23.1
