name: spry
description: Spry is an HTTP middleware framework for Dart to make web applications and APIs more enjoyable to write.
version: 0.0.9
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
