name: spry
description: Spry is an HTTP middleware framework for Dart to make web applications and APIs more enjoyable to write.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  prexp: ^0.1.0
  stack_trace: ^1.11.0

dev_dependencies:
  lints: ^2.0.0
