name: spry_json
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  spry: ^0.0.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
