name: spry_websocket
description: Spry WebSocket is a Spry handler for handling WebSocket requests.
version: 0.0.0
repository: https://github.com/odroe/spry
homepage: https://spry.fun

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  meta: ^1.9.1
  spry: ">=2.1.1 <3.0.0"
  stream_channel: ^2.1.1
  web_socket_channel: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
