name: spry_interceptor
description: Exception interceptor for Spry, which intercepts exceptions and errors and writes response to prevent unexpected application interruption.
version: 1.0.0
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry_interceptor

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  spry: ^0.5.0
  spry_json: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
