name: Auto upgrade dependabot config
on:
  push:
    branches:
      - main
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      # Install dependencies
      - name: Install dependencies
        run: dart pub get

      # Generate dependabot config to output
      - name: Generate dependabot config
        id: generate
        run: echo "generated=$(dart run scripts/generate_dependabot_config.dart)" >> $GITHUB_OUTPUT

      # Commit and push changes
      - name: Commit and push changes
        if: steps.generate.outputs.generated == 'true'
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull
          git add .
          git commit -s -m "chore(ci): auto upgrade dependabot config"
          git push
  