name: Auto upgrade dependabot config
on:
  push:
    branches:
      - main
env:
  generated: generated_depemdabot.yml
jobs:
  # Generate new dependabot config
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      # Install dependencies
      - name: Install dependencies
        run: dart pub get

      # Generate dependabot config to output
      - name: Generate dependabot config
        run: dart run scripts/generate_dependabot_config.dart > $generated

      # Upload generated dependabot config
      - name: Upload generated dependabot config
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.generated }}
          path: ${{ env.generated }}

  # Compare generated dependabot config with the one in the repository
  compare:
    runs-on: ubuntu-latest
    needs: [generate]
    outputs:
      same: ${{ steps.compare.outputs.same }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.generated }}
          path: artifacts

      - name: Compare generated dependabot config with the one in the repository
        id: compare
        run: |
          if [[ ${{ hashFiles('.github/dependabot.yml') }} == ${{ hashFiles('artifacts/' + env.generated) }} ]]; then
            echo "same=true" >> $GITHUB_OUTPUT
          else
            echo "same=false" >> $GITHUB_OUTPUT
          fi

  # Upgrade dependabot config
  upgrade:
    runs-on: ubuntu-latest
    needs: [compare]
    if: needs.compare.outputs.same == 'false'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.generated }}
          path: artifacts
      
      - name: Replace dependabot config
        run: cat artifacts/${{ env.generated }} > .github/dependabot.yml
      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .github/dependabot.yml
          git commit -s -m "chore(CI): upgrade dependabot config"
      - name: Push changes
        run: git push
        
    
